
# remove headers that can't be parse by CppHeaderParser
HEADERS_TO_EXCLUDE = [
    'TCollection_AVLNode.hxx',
    'AdvApp2Var_Data_f2c.hxx',
    'NCollection_DataMap.hxx',
    'NCollection_DoubleMap.hxx',
    'NCollection_IndexedDataMap.hxx',
    'NCollection_IndexedMap.hxx', 'NCollection_Map.hxx',
    'NCollection_CellFilter.hxx',
    'NCollection_EBTree.hxx',
    'NCollection_BaseSequence.hxx',
    'NCollection_Haft.h',
    'NCollection_StlIterator.hxx',
    'Standard_StdAllocator.hxx',
    'Standard_CLocaleSentry.hxx',
    'BOPTools_DataMapOfShapeSet.hxx',
    'Resource_gb2312.h', 'Resource_Shiftjis.h',
    'TopOpeBRepBuild_SplitShapes.hxx',
    'TopOpeBRepBuild_SplitSolid.hxx',
    'TopOpeBRepBuild_Builder.hxx',
    'TopOpeBRepBuild_SplitEdge.hxx',
    'TopOpeBRepBuild_Fill.hxx',
    'TopOpeBRepBuild_SplitFace.hxx',
    'TopOpeBRepDS_traceDSX.hxx',
    'ChFiKPart_ComputeData_ChAsymPlnCon.hxx',
    'ChFiKPart_ComputeData_ChAsymPlnCyl.hxx',
    'ChFiKPart_ComputeData_ChAsymPlnPln.hxx',
    'ChFiKPart_ComputeData_ChPlnCon.hxx',
    'ChFiKPart_ComputeData_ChPlnCyl.hxx',
    'ChFiKPart_ComputeData_ChPlnPln.hxx',
    'ChFiKPart_ComputeData_Sphere.hxx',
    'Font_FTFont.hxx', 'Font_FTLibrary.hxx',
    'IntTools_LineConstructor.hxx',
    'IntTools_PolyhedronTool.hxx',
    'IntPatch_PolyhedronTool.hxx',
    'IntPatch_TheInterfPolyhedron.hxx',
    'SelectMgr_CompareResults.hxx',
    'InterfaceGraphic_wntio.hxx',
    'Interface_STAT.hxx',
    'Aspect_DisplayConnection.hxx',
    'XSControl_Vars.hxx',
    'MeshVS_Buffer.hxx',
    'SMDS_SetIterator.hxx',
    'SMESH_Block.hxx',
    'SMESH_ExceptHandlers.hxx', 'StdMeshers_Penta_3D.hxx',
    'SMESH_ControlsDef.hxx',
    'SMESH_Algo.hxx',
    'SMESH_0D_Algo.hxx', 'SMESH_1D_Algo.hxx',
    'SMESH_2D_Algo.hxx',
    'SMESH_3D_Algo.hxx',
    'IntTools_CurveRangeSampleMapHasher.hxx',
    'Interface_ValueInterpret.hxx',
    'StepToTopoDS_DataMapOfRI.hxx',
    'StepToTopoDS_DataMapOfTRI.hxx',
    'StepToTopoDS_DataMapOfRINames.hxx',
    'StepToTopoDS_PointEdgeMap.hxx',
    'StepToTopoDS_PointVertexMap.hxx'
    # New excludes for 0.17
    'NCollection_StlIterator.hxx',
    # 'BOPAlgo_MakerVolume.hxx',
    'BOPTools_CoupleOfShape.hxx',
    'BRepApprox_SurfaceTool.hxx',
    'BRepBlend_HCurveTool.hxx',
    'BRepBlend_HCurve2dTool.hxx',
    'BRepMesh_FaceAttribute.hxx',
    'ChFiKPart_ComputeData_FilPlnCon.hxx',
    'ChFiKPart_ComputeData_FilPlnPln.hxx',
    'ChFiKPart_ComputeData_FilPlnCyl.hxx',
    'ChFiKPart_ComputeData_Rotule.hxx',
    'PrsMgr_ListOfPresentableObjects.hxx',
    'PrsMgr_PresentableObject.hxx',
    'TDF_LabelMapHasher.hxx'
]


# some typedefs parsed by CppHeader can't be wrapped
# and generate SWIG syntax errors. We just forget
# about wrapping those typedefs
TYPEDEFS_TO_EXCLUDE = [
    'NCollection_DelMapNode',
    'BOPDS_DataMapOfPaveBlockCommonBlock',
    'IntWalk_VectorOfWalkingData',
    'IntWalk_VectorOfInteger'
]
